//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferObject.Localize
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTransferObject.Localize.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AADHAAR Number is last four digits..
        /// </summary>
        public static string AadhaarNoDigit
        {
            get
            {
                return ResourceManager.GetString("AadhaarNoDigit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Army Number is five digits..
        /// </summary>
        public static string ArmyNumberDigit
        {
            get
            {
                return ResourceManager.GetString("ArmyNumberDigit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Army Number is five digits..
        /// </summary>
        public static string GISOfficerArmyNumber
        {
            get
            {
                return ResourceManager.GetString("GISOfficerArmyNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value for {0} must be between {1} and {2}.
        /// </summary>
        public static string HtError
        {
            get
            {
                return ResourceManager.GetString("HtError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Army Number is five digits..
        /// </summary>
        public static string InitiatingOfficerDigit
        {
            get
            {
                return ResourceManager.GetString("InitiatingOfficerDigit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        public static string InvalidEmailError
        {
            get
            {
                return ResourceManager.GetString("InvalidEmailError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid user format.
        /// </summary>
        public static string InvalidUserError
        {
            get
            {
                return ResourceManager.GetString("InvalidUserError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum length of {0} is &apos;{1}&apos; characters..
        /// </summary>
        public static string MaxLengthError
        {
            get
            {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Min Age.
        /// </summary>
        public static string MinAgeError
        {
            get
            {
                return ResourceManager.GetString("MinAgeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minimum length of {0} is &apos;{1}&apos; characters..
        /// </summary>
        public static string MinLengthError
        {
            get
            {
                return ResourceManager.GetString("MinLengthError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only Number Allowed..
        /// </summary>
        public static string OnlyNumber
        {
            get
            {
                return ResourceManager.GetString("OnlyNumber", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Only alphabets and numbers are allowed.
        /// </summary>
        public static string AlphaNumericOnly
        {
            get
            {
                return ResourceManager.GetString("AlphaNumericOnly", resourceCulture);
            }
        }
        public static string Alphawithspace
        {
            get
            {
                return ResourceManager.GetString("Alphawithspace", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Only alphabets and numbers are allowed.
        /// </summary>
        public static string StrongPassword
        {
            get
            {
                return ResourceManager.GetString("StrongPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredError
        {
            get
            {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select {0}..
        /// </summary>
        public static string RequiredSelectError
        {
            get
            {
                return ResourceManager.GetString("RequiredSelectError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Special chars not allowed for security reasons..
        /// </summary>
        public static string SpecialChars
        {
            get
            {
                return ResourceManager.GetString("SpecialChars", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Special chars not allowed except / -. :..
        /// </summary>
        public static string SpecialCharsWithSymbol
        {
            get
            {
                return ResourceManager.GetString("SpecialCharsWithSymbol", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please accept the terms and condition..
        /// </summary>
        public static string TermsConditionsError
        {
            get
            {
                return ResourceManager.GetString("TermsConditionsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} is seven digits..
        /// </summary>
        public static string UnitSusNoDigit
        {
            get
            {
                return ResourceManager.GetString("UnitSusNoDigit", resourceCulture);
            }
        }
    }
}
