//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataTransferObject.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataTransferObject.Localize.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AADHAAR No.
        /// </summary>
        public static string AadhaarNo {
            get {
                return ResourceManager.GetString("AadhaarNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string Appointment {
            get {
                return ResourceManager.GetString("Appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Name.
        /// </summary>
        public static string AppointmentName {
            get {
                return ResourceManager.GetString("AppointmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arm / Service.
        /// </summary>
        public static string ArmService {
            get {
                return ResourceManager.GetString("ArmService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army Number.
        /// </summary>
        public static string ArmyNumber {
            get {
                return ResourceManager.GetString("ArmyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string BasicDetailId {
            get {
                return ResourceManager.GetString("BasicDetailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bde..
        /// </summary>
        public static string Bde {
            get {
                return ResourceManager.GetString("Bde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string BloodGroup {
            get {
                return ResourceManager.GetString("BloodGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Choice.
        /// </summary>
        public static string choice {
            get {
                return ResourceManager.GetString("choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comd..
        /// </summary>
        public static string Comd {
            get {
                return ResourceManager.GetString("Comd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corps..
        /// </summary>
        public static string Corps {
            get {
                return ResourceManager.GetString("Corps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Commissioning/ Enrollment.
        /// </summary>
        public static string DateOfCommissioning {
            get {
                return ResourceManager.GetString("DateOfCommissioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Issue.
        /// </summary>
        public static string DateOfIssue {
            get {
                return ResourceManager.GetString("DateOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string DistrictId {
            get {
                return ResourceManager.GetString("DistrictId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Div..
        /// </summary>
        public static string Div {
            get {
                return ResourceManager.GetString("Div", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Name.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Word Document.
        /// </summary>
        public static string DocPath {
            get {
                return ResourceManager.GetString("DocPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string DocUploadId {
            get {
                return ResourceManager.GetString("DocUploadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Id.
        /// </summary>
        public static string DomainId {
            get {
                return ResourceManager.GetString("DomainId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id..
        /// </summary>
        public static string EmailId {
            get {
                return ResourceManager.GetString("EmailId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIS Officer Appointment.
        /// </summary>
        public static string GISAppointment {
            get {
                return ResourceManager.GetString("GISAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIS Officer Name.
        /// </summary>
        public static string GISName {
            get {
                return ResourceManager.GetString("GISName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIS Rep Officer ArmyNumber.
        /// </summary>
        public static string GISOfficerArmyNumber {
            get {
                return ResourceManager.GetString("GISOfficerArmyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIS Officer Rank.
        /// </summary>
        public static string GISRank {
            get {
                return ResourceManager.GetString("GISRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIS Officer Formation / Unit .
        /// </summary>
        public static string GISUnitFormation {
            get {
                return ResourceManager.GetString("GISUnitFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height (Cm).
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Mark.
        /// </summary>
        public static string IdentityMark {
            get {
                return ResourceManager.GetString("IdentityMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Army No..
        /// </summary>
        public static string InitiatingOfficerArmyNumber {
            get {
                return ResourceManager.GetString("InitiatingOfficerArmyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Appointment.
        /// </summary>
        public static string IOAppointment {
            get {
                return ResourceManager.GetString("IOAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Name.
        /// </summary>
        public static string IOName {
            get {
                return ResourceManager.GetString("IOName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Rank.
        /// </summary>
        public static string IORank {
            get {
                return ResourceManager.GetString("IORank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Formation / Unit .
        /// </summary>
        public static string IOUnitFormation {
            get {
                return ResourceManager.GetString("IOUnitFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuing Authority.
        /// </summary>
        public static string IssuingAuth {
            get {
                return ResourceManager.GetString("IssuingAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string Observations {
            get {
                return ResourceManager.GetString("Observations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permt Address as per Service Records.
        /// </summary>
        public static string PermanentAddress {
            get {
                return ResourceManager.GetString("PermanentAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Photo_ {
            get {
                return ResourceManager.GetString("Photo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BROWSE &amp; UPLOAD PHOTOGRAPH.
        /// </summary>
        public static string PhotoImagePath {
            get {
                return ResourceManager.GetString("PhotoImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Issue.
        /// </summary>
        public static string PlaceOfIssue {
            get {
                return ResourceManager.GetString("PlaceOfIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string ProfileDataId {
            get {
                return ResourceManager.GetString("ProfileDataId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regimental.
        /// </summary>
        public static string RegimentalId {
            get {
                return ResourceManager.GetString("RegimentalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string RegistrationType {
            get {
                return ResourceManager.GetString("RegistrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seniority.
        /// </summary>
        public static string Seniority {
            get {
                return ResourceManager.GetString("Seniority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Army No.
        /// </summary>
        public static string ServiceNo {
            get {
                return ResourceManager.GetString("ServiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature_ {
            get {
                return ResourceManager.GetString("Signature_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature of Indl.
        /// </summary>
        public static string SignatureImagePath {
            get {
                return ResourceManager.GetString("SignatureImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S No..
        /// </summary>
        public static string Sno {
            get {
                return ResourceManager.GetString("Sno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string StateId {
            get {
                return ResourceManager.GetString("StateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Type.
        /// </summary>
        public static string SubmitType {
            get {
                return ResourceManager.GetString("SubmitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///		
        ///		
        ///	
        ///	.
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Of Unit.
        /// </summary>
        public static string TypeOfUnit {
            get {
                return ResourceManager.GetString("TypeOfUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit SUS No..
        /// </summary>
        public static string UnitSusNo {
            get {
                return ResourceManager.GetString("UnitSusNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string UserId {
            get {
                return ResourceManager.GetString("UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
    }
}
